Windows build, update comments

diff --git a/generate_makefile b/generate_makefile
--- a/generate_makefile
+++ b/generate_makefile
@@ -2,8 +2,8 @@
 cd "$(dirname "$0")"
 type premake5 >/dev/null 2>&1 ||
 {
-	echo >&2 "'premake4' not found in your path.";
-	echo >&2 "Premake can be downloaded from http://industriousone.com/premake/";
+	echo >&2 "'premake5' not found in your path.";
+	echo >&2 "Premake can be downloaded from https://premake.github.io/download.html";
 	exit 1;
 }
 premake5 --file=premake.lua gmake
